"""Reviewed built-in Linux adapter and tool manifests.

The registry is data-only. Adapter builders and the execution authority remain
separate so a model or project directory cannot add capabilities at runtime.
"""
from __future__ import annotations

from typing import Any

TOOL_CATALOG: dict[str, dict[str, Any]] = {
    "git": {"family": "development", "probe": ["--version"], "role": "version-control"},
    "ss": {"family": "network", "probe": ["-V"], "role": "socket inspection"},
    "ip": {"family": "network", "probe": ["-Version"], "role": "network facts"},
    "systemctl": {"family": "systemd", "probe": ["--version"], "role": "service inspection"},
    "journalctl": {"family": "systemd", "probe": ["--version"], "role": "bounded logs"},
    "df": {"family": "filesystem", "probe": ["--version"], "role": "filesystem usage"},
    "du": {"family": "filesystem", "probe": ["--version"], "role": "directory usage"},
    "ls": {"family": "filesystem", "probe": ["--version"], "role": "directory listing"},
    "tail": {"family": "filesystem", "probe": ["--version"], "role": "bounded log reading"},
    "findmnt": {"family": "filesystem", "probe": ["--version"], "role": "mounted filesystem facts"},
    "pwd": {"family": "system", "probe": ["--version"], "role": "working directory"},
    "whoami": {"family": "system", "probe": ["--version"], "role": "current user"},
    "id": {"family": "system", "probe": ["--version"], "role": "user identity"},
    "hostname": {"family": "system", "probe": ["--version"], "role": "host name"},
    "ps": {"family": "system", "probe": ["--version"], "role": "process facts"},
    "python3": {"family": "development", "probe": ["--version"], "role": "python runtime"},
    "gcc": {"family": "development", "probe": ["--version"], "role": "compiler"},
    "lsblk": {"family": "system", "probe": ["--version"], "role": "block storage facts"},
    "lsusb": {"family": "system", "probe": ["--version"], "role": "USB device facts"},
    "nft": {"family": "network", "probe": ["--version"], "role": "firewall rules"},
    "iptables": {"family": "network", "probe": ["--version"], "role": "firewall rules"},
    "nmcli": {"family": "network", "probe": ["--version"], "role": "wifi/network facts"},
    "iw": {"family": "network", "probe": ["--version"], "role": "wireless facts"},
    "nslookup": {"family": "network", "probe": ["-version"], "role": "DNS lookup"},
    "dig": {"family": "network", "probe": ["-v"], "role": "DNS lookup"},
    "whois": {"family": "network", "probe": ["--version"], "role": "registry lookup"},
    "free": {"family": "system", "probe": ["--version"], "role": "memory facts"},
    "date": {"family": "system", "probe": ["--version"], "role": "clock facts"},
    "uname": {"family": "system", "probe": ["-a"], "role": "kernel facts"},
    "uptime": {"family": "system", "probe": ["--version"], "role": "load facts"},
    "cat": {"family": "system", "probe": ["--version"], "role": "read observed files"},
    "lscpu": {"family": "system", "probe": ["--version"], "role": "processor facts"},
    "who": {"family": "system", "probe": ["--version"], "role": "current login sessions"},
    "last": {"family": "system", "probe": ["--version"], "role": "login history"},
    "vmstat": {"family": "system", "probe": ["--version"], "role": "virtual memory statistics"},
    "sqlmap": {"family": "authorized-assessment", "probe": ["--version"], "role": "SQL injection testing"},
    "gobuster": {"family": "authorized-content-discovery", "probe": ["version"], "role": "bounded content discovery"},
    "tshark": {"family": "network", "probe": ["--version"], "role": "packet capture analysis"},
    "tcpdump": {"family": "network", "probe": ["--version"], "role": "packet capture"},
    "john": {"family": "analysis", "probe": ["--list=build-info"], "role": "hash analysis"},
    "hashcat": {"family": "analysis", "probe": ["--version"], "role": "hash analysis"},
    "msfconsole": {"family": "authorized-assessment", "probe": ["--version"], "role": "metasploit console"},
    "nmap": {"family": "authorized-reconnaissance", "probe": ["--version"], "role": "scoped service discovery"},
    "nuclei": {"family": "authorized-assessment", "probe": ["-version"], "role": "reviewed template checks"},
    "curl": {"family": "authorized-http", "probe": ["--version"], "role": "HTTP/TLS discovery"},
    "ping": {"family": "network", "probe": ["-V"], "role": "bounded host reachability"},
    "ffuf": {"family": "authorized-content-discovery", "probe": ["-V"], "role": "bounded content discovery"},
    "nikto": {"family": "authorized-assessment", "probe": ["-Version"], "role": "web server assessment"},
    "amass": {"family": "passive-osint", "probe": ["-version"], "role": "passive domain discovery"},
    "ssh": {"family": "ssh-diagnostics", "probe": ["-V"], "role": "connection diagnostics"},
    "apt-get": {"family": "packages", "probe": ["--version"], "role": "package planning and mutation"},
    "apt-cache": {"family": "packages", "probe": ["--version"], "role": "package metadata"},
    "dpkg-query": {"family": "packages", "probe": ["--version"], "role": "installed package facts"},
    "dpkg": {"family": "packages", "probe": ["--version"], "role": "dpkg consistency facts"},
    "apt-mark": {"family": "packages", "probe": ["--version"], "role": "held package facts"},
    "docker": {"family": "containers", "probe": ["--version"], "role": "container inspection"},
    "podman": {"family": "containers", "probe": ["--version"], "role": "container inspection"},
}


ADAPTER_MANIFESTS: dict[str, dict[str, Any]] = {
    "linux.system.health": {"version": "1", "family": "system", "tool": "multiple", "risk": "low", "network_class": "no-network", "operation": "read-only host facts", "limits": {"commands": 4, "timeout_seconds": 30}},
    "linux.system.identity": {"version": "1", "family": "system", "tool": "whoami+id+hostname+pwd", "risk": "low", "network_class": "no-network", "operation": "read-only identity facts", "limits": {"commands": 4, "timeout_seconds": 15}},
    "linux.system.processes": {"version": "1", "family": "system", "tool": "ps", "risk": "low", "network_class": "no-network", "operation": "read-only process facts", "limits": {"timeout_seconds": 15}},
    "linux.filesystem.list": {"version": "1", "family": "filesystem", "tool": "ls", "risk": "low", "network_class": "no-network", "operation": "read-only directory listing", "limits": {"timeout_seconds": 15}},
    "linux.filesystem.log": {"version": "1", "family": "filesystem", "tool": "tail", "risk": "low", "network_class": "no-network", "operation": "bounded log file reading", "limits": {"tail_lines": 200, "timeout_seconds": 15, "output_cap_bytes": 262144}},
    "linux.network.facts": {"version": "1", "family": "network", "tool": "ip", "risk": "low", "network_class": "no-network", "operation": "read-only link, neighbor, and socket facts", "limits": {"timeout_seconds": 15}},
    "linux.systemd.journal": {"version": "1", "family": "systemd", "tool": "journalctl", "risk": "low", "network_class": "no-network", "operation": "bounded journal reading", "limits": {"journal_lines": 100, "timeout_seconds": 30}},
    "linux.filesystem.read": {"version": "1", "family": "filesystem", "tool": "cat", "risk": "low", "network_class": "no-network", "operation": "bounded read-only file inspection", "limits": {"timeout_seconds": 15, "output_cap_bytes": 262144}},
    "linux.system.packages": {"version": "1", "family": "packages", "tool": "dpkg-query", "risk": "low", "network_class": "no-network", "operation": "read-only installed package inventory", "limits": {"timeout_seconds": 30}},
    "linux.system.storage": {"version": "1", "family": "system", "tool": "lsblk", "risk": "low", "network_class": "no-network", "operation": "read-only block storage facts", "limits": {"timeout_seconds": 15}},
    "linux.system.hardware": {"version": "1", "family": "system", "tool": "lsusb", "risk": "low", "network_class": "no-network", "operation": "read-only USB device facts", "limits": {"timeout_seconds": 15}},
    "linux.development.git-log": {"version": "1", "family": "development", "tool": "git", "risk": "low", "network_class": "no-network", "operation": "read-only commit history", "limits": {"commits": 50, "timeout_seconds": 30}},
    "linux.development.git-branches": {"version": "1", "family": "development", "tool": "git", "risk": "low", "network_class": "no-network", "operation": "read-only branch listing", "limits": {"timeout_seconds": 30}},
    "linux.development.git-diff": {"version": "1", "family": "development", "tool": "git", "risk": "low", "network_class": "no-network", "operation": "read-only repository diff", "limits": {"timeout_seconds": 30}},
    "linux.network.routes": {"version": "1", "family": "network", "tool": "ip", "risk": "low", "network_class": "no-network", "operation": "read-only routing table", "limits": {"timeout_seconds": 15}},
    "linux.network.firewall": {"version": "1", "family": "network", "tool": "nft+iptables", "risk": "low", "network_class": "no-network", "operation": "read-only firewall rules", "limits": {"timeout_seconds": 15}},
    "linux.network.wifi": {"version": "1", "family": "network", "tool": "nmcli+iw", "risk": "low", "network_class": "no-network", "operation": "read-only wireless facts", "limits": {"timeout_seconds": 15}},
    "linux.network.dns": {"version": "1", "family": "network", "tool": "nslookup+dig", "risk": "high", "network_class": "outbound-read", "operation": "bounded DNS lookup", "limits": {"timeout_seconds": 15}},
    "linux.network.whois": {"version": "1", "family": "network", "tool": "whois", "risk": "high", "network_class": "outbound-read", "operation": "bounded registry lookup", "limits": {"timeout_seconds": 15}},
    "linux.filesystem.usage": {"version": "1", "family": "filesystem", "tool": "df+du", "risk": "low", "network_class": "no-network", "operation": "read-only filesystem facts", "limits": {"depth": 1, "timeout_seconds": 30}},
    "linux.network.sockets": {"version": "1", "family": "network", "tool": "ss", "risk": "low", "network_class": "no-network", "operation": "read-only local socket facts", "limits": {"timeout_seconds": 30}},
    "linux.network.interfaces": {"version": "1", "family": "network", "tool": "ip", "risk": "low", "network_class": "no-network", "operation": "read-only interface facts", "limits": {"timeout_seconds": 15}},
    "linux.system.clock": {"version": "1", "family": "system", "tool": "date", "risk": "low", "network_class": "no-network", "operation": "read-only clock facts", "limits": {"timeout_seconds": 5}},
    "linux.system.os-release": {"version": "1", "family": "system", "tool": "cat", "risk": "low", "network_class": "no-network", "operation": "read-only os-release facts", "limits": {"timeout_seconds": 5}},
    "linux.system.cpu": {"version": "1", "family": "system", "tool": "lscpu", "risk": "low", "network_class": "no-network", "operation": "read-only processor facts", "limits": {"timeout_seconds": 10}},
    "linux.system.login": {"version": "1", "family": "system", "tool": "who+last", "risk": "low", "network_class": "no-network", "operation": "read-only login sessions", "limits": {"timeout_seconds": 15}},
    "linux.development.git-status": {"version": "1", "family": "development", "tool": "git", "risk": "low", "network_class": "no-network", "operation": "read-only repository facts", "limits": {"timeout_seconds": 30}},
    "linux.systemd.inspect": {"version": "1", "family": "systemd", "tool": "systemctl+journalctl", "risk": "low", "network_class": "no-network", "operation": "read-only unit and journal facts", "limits": {"journal_lines": 80, "timeout_seconds": 30}},
    "linux.systemd.mutate": {"version": "1", "family": "systemd", "tool": "systemctl", "risk": "high", "network_class": "no-network", "operation": "guarded service mutation", "privilege": "root-required", "limits": {"timeout_seconds": 60}},
    "linux.packages.apt": {"version": "1", "family": "packages", "tool": "apt-get+apt-cache+dpkg-query+dpkg+apt-mark", "risk": "high", "network_class": "outbound-mutation", "operation": "guarded apt package operation", "privilege": "root-required", "limits": {"timeout_seconds": 900}},
    "linux.containers.diagnose": {"version": "1", "family": "containers", "tool": "docker+podman", "risk": "low", "network_class": "loopback-only", "operation": "read-only container runtime diagnosis", "limits": {"commands": 3, "timeout_seconds": 30}},
    "linux.containers.inspect": {"version": "1", "family": "containers", "tool": "docker+podman", "risk": "low", "network_class": "loopback-only", "operation": "read-only container inspection", "limits": {"output_cap_bytes": 524288, "timeout_seconds": 30}},
    "linux.containers.logs": {"version": "1", "family": "containers", "tool": "docker+podman", "risk": "low", "network_class": "loopback-only", "operation": "bounded container logs", "limits": {"tail_lines": 200, "timeout_seconds": 30}},
    "linux.ssh.config": {"version": "1", "family": "ssh-diagnostics", "tool": "ssh", "risk": "low", "network_class": "no-network", "operation": "read-only SSH configuration resolution", "limits": {"timeout_seconds": 15}},
    "linux.ssh.connection": {"version": "1", "family": "ssh-diagnostics", "tool": "ssh", "risk": "high", "network_class": "outbound-read", "operation": "bounded SSH connectivity diagnostic", "limits": {"connect_timeout_seconds": 5, "timeout_seconds": 15}},
    "security.nmap.discovery": {"version": "1", "family": "authorized-reconnaissance", "tool": "nmap", "risk": "high", "network_class": "outbound-read", "operation": "scoped service discovery", "limits": {"max_cidr_hosts": 256, "max_ports": 32, "timing": "T2", "timeout_seconds": 120}},
    "security.http.headers": {"version": "1", "family": "authorized-http", "tool": "curl", "risk": "high", "network_class": "outbound-read", "operation": "bounded HTTP/TLS header discovery", "limits": {"max_time_seconds": 15, "max_redirects": 0}},
    "linux.network.ping": {"version": "1", "family": "network", "tool": "ping", "risk": "high", "network_class": "outbound-read", "operation": "bounded host reachability", "limits": {"packets": 2, "timeout_seconds": 15}},
    "security.nuclei.templates": {"version": "1", "family": "authorized-assessment", "tool": "nuclei", "risk": "high", "network_class": "outbound-read", "operation": "reviewed template checks against one scoped URL", "limits": {"timeout_seconds": 180, "rate_limit": 5, "concurrency": 2}},
    "security.nikto.web": {"version": "1", "family": "authorized-assessment", "tool": "nikto", "risk": "high", "network_class": "outbound-read", "operation": "bounded web server assessment", "limits": {"timeout_seconds": 180, "maxtime": "120s"}},
    "security.amass.passive": {"version": "1", "family": "passive-osint", "tool": "amass", "risk": "high", "network_class": "outbound-read", "operation": "passive domain enumeration", "limits": {"timeout_seconds": 180, "mode": "passive"}},
    "security.ffuf.discovery": {"version": "1", "family": "authorized-content-discovery", "tool": "ffuf", "risk": "high", "network_class": "outbound-read", "operation": "bounded content discovery with a host wordlist", "limits": {"timeout_seconds": 180, "threads": 10}},
    "security.gobuster.discovery": {"version": "1", "family": "authorized-content-discovery", "tool": "gobuster", "risk": "high", "network_class": "outbound-read", "operation": "bounded directory discovery with a host wordlist", "limits": {"timeout_seconds": 180, "threads": 10}},
}

