'use strict';
const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync(require('path').join(__dirname, '..', 'frontend', 'terminal.js'), 'utf8');
const context = { window: {} };
vm.runInNewContext(source, context);
const Terminal = context.window.VortexTerminal;
assert.ok(Terminal);
const terminal = new Terminal(12, 3, 20);
terminal.feed('\x1b[31mred\x1b[0m plain');
assert.strictEqual(terminal.screen()[0][0].fg, 1);
assert.strictEqual(terminal.screen()[0][4].fg, null);
terminal.feed('\x1b[2J\x1b[2;4Hok');
assert.strictEqual(terminal.screen()[1][3].ch, 'o');
assert.strictEqual(terminal.screen()[1][4].ch, 'k');
terminal.feed('\x1b[?1049hALT');
assert.strictEqual(terminal.useAlternate, true);
assert.strictEqual(terminal.screen()[0][0].ch, 'A');
terminal.feed('\x1b[?1049l');
assert.strictEqual(terminal.useAlternate, false);
terminal.feed('one\ntwo\nthree\nfour');
assert.ok(terminal.scrollback.length > 0);
terminal.feed('\x1b]0;not a title\x07visible');
assert.ok(terminal.screen().some(row => row.some(cell => cell.ch === 'v')));
console.log('terminal emulator tests: PASS');
