#!/usr/bin/env bash
set -euo pipefail
# Release packaging is intentionally not a fake build: run this on a pinned
# pinned Linux builder after the Python/Electron dependency policy is finalized.
root=$(cd "$(dirname "$0")/../.." && pwd)
out="${1:-$root/dist/deb}"
mkdir -p "$out"
echo "Packaging blocker: signed .deb assembly is Phase 7 and requires a pinned Linux builder."
echo "Source root: $root"
echo "No package was generated by this scaffold."
exit 2
