"""Normalized definitions for every AI provider Vortex knows how to talk to.

A definition describes HOW to reach a provider, how to discover its models,
and what is honestly known about its pricing and requirements.

Discovery Catalogue:
    Vortex utilizes `open-free-llm-api/awesome-freellm-apis` (https://freellm.net/)
    as its reference free-model discovery catalogue.

Free Status Categories:
    * "LOCAL_$0"                - Local inference on this host. $0 forever.
    * "FREE_NO_CARD"            - Free API tier with no credit card required.
    * "FREE_REGISTRATION"       - Free API tier requiring basic account registration.
    * "FREE_PHONE_VERIFICATION" - Free API tier requiring phone verification.
    * "FREE_RATE_LIMITED"       - Free API tier with strict request/minute and request/day rate limits.
    * "FREE_BILLABLE_OVERAGE"   - Free quota tier that may incur billable overage if exceeded.
    * "RENEWABLE_CREDITS"       - Periodic renewable credits (e.g., monthly credit reset).
    * "TRIAL_ONLY"              - Expiring trial credit or limited time promotional trial.
    * "PAID"                    - Paid-only provider or model.
    * "UNKNOWN"                 - Pricing cannot be verified automatically. Disabled in FREE-ONLY mode.
"""
from __future__ import annotations

from typing import Any

DEFAULT_LOCAL_MODEL = "qwen2.5:3b"
OLLAMA_LOCAL_ENDPOINT = "http://127.0.0.1:11434"

GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

# Free status categories
STATUS_LOCAL_0 = "LOCAL_$0"
STATUS_FREE_NO_CARD = "FREE_NO_CARD"
STATUS_FREE_REGISTRATION = "FREE_REGISTRATION"
STATUS_FREE_PHONE_VERIFICATION = "FREE_PHONE_VERIFICATION"
STATUS_FREE_RATE_LIMITED = "FREE_RATE_LIMITED"
STATUS_FREE_BILLABLE_OVERAGE = "FREE_BILLABLE_OVERAGE"
STATUS_RENEWABLE_CREDITS = "RENEWABLE_CREDITS"
STATUS_TRIAL_ONLY = "TRIAL_ONLY"
STATUS_PAID = "PAID"
STATUS_UNKNOWN = "UNKNOWN"

# Gemini free-tier model families per Google AI Studio pricing:
# Flash / Flash-Lite model IDs carry a $0 free-tier row within daily quotas;
# Pro models are paid-only. Re-verified at discovery time.
GEMINI_FREE_TIER_PATTERNS = ("flash", "flash-lite")
GEMINI_PAID_ONLY_PATTERNS = ("pro", "ultra", "deep-think")

# Default Gemini logical entries: 3 distinct entries served by up to 3 keys.
# Model IDs verified against live Google AI Studio catalog.
GEMINI_DEFAULT_ENTRIES: dict[str, dict[str, str]] = {
    "gemini-1": {"model": "gemini-2.5-flash", "key_slot": "GEMINI_API_KEY_1"},
    "gemini-2": {"model": "gemini-2.0-flash", "key_slot": "GEMINI_API_KEY_2"},
    "gemini-3": {"model": "gemini-1.5-flash", "key_slot": "GEMINI_API_KEY_1"},
}

# Canonical provider definitions across all 30 catalogue providers.
# "api" selects transport adapter: ollama | openai | gemini | cloudflare
# "discovery" selects model enumeration: ollama-tags | openai-models | openrouter-models | gemini-models | cloudflare-models | static
PROVIDER_DEFS: list[dict[str, Any]] = [
    {
        "id": "ollama-local",
        "name": "Local Ollama (Qwen 2.5 3B)",
        "family": "ollama",
        "mode": "local",
        "api": "ollama",
        "base_url": OLLAMA_LOCAL_ENDPOINT,
        "key_slot": None,
        "discovery": "ollama-tags",
        "free_status": STATUS_LOCAL_0,
        "free_category": STATUS_LOCAL_0,
        "free_detail": "Local offline inference on this machine via loopback Ollama. $0 forever, 100% private.",
        "rate_limits": "Uncapped local compute",
        "context_length": 32768,
        "requires_api_key": False,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": True,
        "priority": 0,
        "default_model": DEFAULT_LOCAL_MODEL,
        "source_url": "https://ollama.com",
    },
    {
        "id": "gemini-1",
        "name": "Gemini #1 (Flash 2.5)",
        "family": "google-gemini",
        "mode": "cloud",
        "api": "gemini",
        "base_url": GEMINI_BASE_URL,
        "key_slot": "GEMINI_API_KEY_1",
        "discovery": "gemini-models",
        "free_status": STATUS_FREE_RATE_LIMITED,
        "free_category": STATUS_FREE_RATE_LIMITED,
        "free_detail": "Google AI Studio free tier: 10-15 RPM, 250-1500 RPD on Flash models. Pro models paid-only.",
        "rate_limits": "10-15 RPM / 250-1500 RPD",
        "context_length": 1048576,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": True,
        "priority": 10,
        "default_model": GEMINI_DEFAULT_ENTRIES["gemini-1"]["model"],
        "source_url": "https://aistudio.google.com/apikey",
    },
    {
        "id": "gemini-2",
        "name": "Gemini #2 (Flash 2.0)",
        "family": "google-gemini",
        "mode": "cloud",
        "api": "gemini",
        "base_url": GEMINI_BASE_URL,
        "key_slot": "GEMINI_API_KEY_2",
        "discovery": "gemini-models",
        "free_status": STATUS_FREE_RATE_LIMITED,
        "free_category": STATUS_FREE_RATE_LIMITED,
        "free_detail": "Google AI Studio free tier (secondary key slot): independent rate limit pool.",
        "rate_limits": "10-15 RPM / 250-1500 RPD",
        "context_length": 1048576,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": True,
        "priority": 11,
        "default_model": GEMINI_DEFAULT_ENTRIES["gemini-2"]["model"],
        "source_url": "https://aistudio.google.com/apikey",
    },
    {
        "id": "gemini-3",
        "name": "Gemini #3 (Flash 1.5)",
        "family": "google-gemini",
        "mode": "cloud",
        "api": "gemini",
        "base_url": GEMINI_BASE_URL,
        "key_slot": "GEMINI_API_KEY_1",   # Shared key or GEMINI_API_KEY_3
        "discovery": "gemini-models",
        "free_status": STATUS_FREE_RATE_LIMITED,
        "free_category": STATUS_FREE_RATE_LIMITED,
        "free_detail": "Google AI Studio free tier: fallback Flash model slot.",
        "rate_limits": "15 RPM / 1500 RPD",
        "context_length": 1048576,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": True,
        "priority": 12,
        "default_model": GEMINI_DEFAULT_ENTRIES["gemini-3"]["model"],
        "source_url": "https://aistudio.google.com/apikey",
    },
    {
        "id": "groq",
        "name": "Groq",
        "family": "groq",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.groq.com/openai/v1",
        "key_slot": "GROQ_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_NO_CARD,
        "free_category": STATUS_FREE_NO_CARD,
        "free_detail": "Groq free plan: ultra-fast LPU inference at $0 with 30 RPM / 14,400 RPD limits. No credit card required.",
        "rate_limits": "30 RPM / 14,400 RPD",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": True,
        "priority": 20,
        "default_model": "llama-3.3-70b-versatile",
        "source_url": "https://console.groq.com/keys",
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "family": "openrouter",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://openrouter.ai/api/v1",
        "key_slot": "OPENROUTER_API_KEY",
        "discovery": "openrouter-models",
        "free_status": STATUS_FREE_RATE_LIMITED,
        "free_category": STATUS_FREE_RATE_LIMITED,
        "free_detail": "Models with ':free' suffix are $0 (20 req/min, 50-200 req/day unfunded). Discovered dynamically.",
        "rate_limits": "20 RPM / 50-200 RPD",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": True,
        "priority": 30,
        "default_model": "",
        "extra_headers": {"HTTP-Referer": "https://github.com/mrtc-solutions/linux-vortex-terminal", "X-Title": "Vortex Terminal"},
        "source_url": "https://openrouter.ai/keys",
    },
    {
        "id": "nvidia-nim",
        "name": "NVIDIA NIM",
        "family": "nvidia",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://integrate.api.nvidia.com/v1",
        "key_slot": "NVIDIA_NIM_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_PHONE_VERIFICATION,
        "free_category": STATUS_FREE_PHONE_VERIFICATION,
        "free_detail": "NVIDIA build.nvidia.com free tier: 40 RPM, 1,000 free API credits. Requires phone number verification.",
        "rate_limits": "40 RPM",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": True,
        "enabled_default": True,
        "priority": 35,
        "default_model": "meta/llama-3.3-70b-instruct",
        "source_url": "https://build.nvidia.com",
    },
    {
        "id": "modelscope",
        "name": "ModelScope",
        "family": "modelscope",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api-inference.modelscope.cn/v1",
        "key_slot": "MODELSCOPE_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_REGISTRATION,
        "free_category": STATUS_FREE_REGISTRATION,
        "free_detail": "Alibaba ModelScope free inference: up to 2,000 calls/day on open models like Qwen and DeepSeek.",
        "rate_limits": "2,000 calls/day",
        "context_length": 32768,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": True,
        "priority": 40,
        "default_model": "Qwen/Qwen2.5-72B-Instruct",
        "source_url": "https://modelscope.cn/my/myaccesstoken",
    },
    {
        "id": "cloudflare",
        "name": "Cloudflare Workers AI",
        "family": "cloudflare",
        "mode": "cloud",
        "api": "cloudflare",
        "base_url": "https://api.cloudflare.com/client/v4",
        "key_slot": "CLOUDFLARE_API_TOKEN",
        "extra_key_slots": ["CLOUDFLARE_ACCOUNT_ID"],
        "discovery": "cloudflare-models",
        "free_status": STATUS_FREE_BILLABLE_OVERAGE,
        "free_category": STATUS_FREE_BILLABLE_OVERAGE,
        "free_detail": "Workers Free plan gives 10,000 neurons/day (~100-300 requests). Note: accounts with payment methods may bill overages.",
        "rate_limits": "10,000 neurons/day",
        "context_length": 32768,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": True,
        "priority": 45,
        "default_model": "@cf/meta/llama-3.1-8b-instruct",
        "source_url": "https://dash.cloudflare.com/profile/api-tokens",
    },
    {
        "id": "pollinations",
        "name": "Pollinations",
        "family": "pollinations",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://text.pollinations.ai/openai",
        "base_is_endpoint": True,
        "key_slot": None,
        "discovery": "static",
        "free_status": STATUS_FREE_NO_CARD,
        "free_category": STATUS_FREE_NO_CARD,
        "free_detail": "Keyless community free API. No sign-up, no credit card. Best-effort availability.",
        "rate_limits": "Fair use community quota",
        "context_length": 65536,
        "requires_api_key": False,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": True,
        "priority": 50,
        "default_model": "openai",
        "static_models": [
            {"id": "openai", "label": "Pollinations default (OpenAI-compatible)", "free": True},
            {"id": "qwen", "label": "Qwen 2.5 72B (Pollinations)", "free": True},
            {"id": "mistral", "label": "Mistral Nemo (Pollinations)", "free": True},
        ],
        "source_url": "https://pollinations.ai",
    },
    {
        "id": "mistral",
        "name": "Mistral AI",
        "family": "mistral",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.mistral.ai/v1",
        "key_slot": "MISTRAL_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_RATE_LIMITED,
        "free_category": STATUS_FREE_RATE_LIMITED,
        "free_detail": "Mistral La Plateforme free tier: 1 RPS on open models (Mistral Small, Nemo, Codestral).",
        "rate_limits": "1 RPS / 2 RPM",
        "context_length": 128000,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 60,
        "default_model": "mistral-small-latest",
        "source_url": "https://console.mistral.ai/api-keys",
    },
    {
        "id": "cohere",
        "name": "Cohere",
        "family": "cohere",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.cohere.ai/compatibility/v1",
        "key_slot": "COHERE_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_RATE_LIMITED,
        "free_category": STATUS_FREE_RATE_LIMITED,
        "free_detail": "Cohere Trial API Key: rate-limited to 1,000 calls/month at $0. Command-R models available.",
        "rate_limits": "1000 calls/month",
        "context_length": 128000,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 61,
        "default_model": "command-r",
        "source_url": "https://dashboard.cohere.com/api-keys",
    },
    {
        "id": "cerebras",
        "name": "Cerebras",
        "family": "cerebras",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.cerebras.ai/v1",
        "key_slot": "CEREBRAS_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_RATE_LIMITED,
        "free_category": STATUS_FREE_RATE_LIMITED,
        "free_detail": "Cerebras Wafer-Scale inference: 30 RPM, 14,400 RPD, ~1M tokens/day on Llama 3.3 70B.",
        "rate_limits": "30 RPM / 14,400 RPD / 1M TPD",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 62,
        "default_model": "llama3.3-70b",
        "source_url": "https://cloud.cerebras.ai",
    },
    {
        "id": "deepseek",
        "name": "DeepSeek",
        "family": "deepseek",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.deepseek.com/v1",
        "key_slot": "DEEPSEEK_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_REGISTRATION,
        "free_category": STATUS_FREE_REGISTRATION,
        "free_detail": "DeepSeek platform: flagship DeepSeek-V3 and DeepSeek-R1 reasoning models.",
        "rate_limits": "Dynamic fair use",
        "context_length": 65536,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 63,
        "default_model": "deepseek-chat",
        "source_url": "https://platform.deepseek.com/api_keys",
    },
    {
        "id": "siliconflow",
        "name": "SiliconFlow",
        "family": "siliconflow",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.siliconflow.com/v1",
        "key_slot": "SILICONFLOW_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_REGISTRATION,
        "free_category": STATUS_FREE_REGISTRATION,
        "free_detail": "SiliconFlow free tier: selected open models with free badges (DeepSeek-V3, Qwen 2.5).",
        "rate_limits": "Dynamic free tier limits",
        "context_length": 65536,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 64,
        "default_model": "deepseek-ai/DeepSeek-V3",
        "source_url": "https://cloud.siliconflow.cn/account/ak",
    },
    {
        "id": "zai",
        "name": "Z AI / Zhipu AI",
        "family": "zai",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.z.ai/api/paas/v4",
        "key_slot": "ZAI_API_KEY",
        "discovery": "static",
        "free_status": STATUS_UNKNOWN,
        "free_category": STATUS_UNKNOWN,
        "free_detail": "Z.ai has offered free GLM Flash models, but pricing metadata is not exposed by the API. FREE STATUS: UNKNOWN — verify terms, then enable manually.",
        "rate_limits": "Free tier quota",
        "context_length": 128000,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 65,
        "default_model": "glm-4.5-flash",
        "static_models": [
            {"id": "glm-4.5-flash", "label": "GLM-4.5 Flash", "free": None},
        ],
        "source_url": "https://open.bigmodel.cn/usercenter/apikeys",
    },
    {
        "id": "sambanova",
        "name": "SambaNova",
        "family": "sambanova",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.sambanova.ai/v1",
        "key_slot": "SAMBANOVA_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_RATE_LIMITED,
        "free_category": STATUS_FREE_RATE_LIMITED,
        "free_detail": "SambaNova Cloud developer tier: fast SN40L inference on Meta Llama and Qwen models.",
        "rate_limits": "Developer tier limits",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 66,
        "default_model": "Meta-Llama-3.3-70B-Instruct",
        "source_url": "https://cloud.sambanova.ai/apis",
    },
    {
        "id": "opencode",
        "name": "OpenCode Zen",
        "family": "opencode",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://opencode.ai/zen/v1",
        "key_slot": "OPENCODE_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_NO_CARD,
        "free_category": STATUS_FREE_NO_CARD,
        "free_detail": "OpenCode Zen developer API: 24 free coding models including DeepSeek-V4 Flash and MiMo.",
        "rate_limits": "Fair use developer quota",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 67,
        "default_model": "deepseek-v4-flash",
        "source_url": "https://opencode.ai/auth",
    },
    {
        "id": "llm7",
        "name": "LLM7.io",
        "family": "llm7",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.llm7.io/v1",
        "key_slot": "LLM7_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_NO_CARD,
        "free_category": STATUS_FREE_NO_CARD,
        "free_detail": "LLM7.io aggregator: 10-30 RPM free tier covering GPT-4o-mini, DeepSeek-R1, and Qwen.",
        "rate_limits": "10-30 RPM / 60 req/hr",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 68,
        "default_model": "gpt-4o-mini",
        "source_url": "https://llm7.io",
    },
    {
        "id": "ollama-cloud",
        "name": "Ollama Cloud",
        "family": "ollama-cloud",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://ollama.com/v1",
        "key_slot": "OLLAMA_CLOUD_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_RATE_LIMITED,
        "free_category": STATUS_FREE_RATE_LIMITED,
        "free_detail": "Ollama Cloud hosted endpoints: free tier has daily usage caps.",
        "rate_limits": "Hourly / daily caps",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 69,
        "default_model": "qwen2.5:3b",
        "source_url": "https://ollama.com",
    },
    {
        "id": "kilo",
        "name": "Kilo Code",
        "family": "kilo",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.kilo.ai/api/gateway",
        "key_slot": "KILO_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_NO_CARD,
        "free_category": STATUS_FREE_NO_CARD,
        "free_detail": "Kilo Code coding gateway: 200 req/hr free tier auto-routing to top coding models.",
        "rate_limits": "200 req/hr",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 70,
        "default_model": "kilo-default",
        "source_url": "https://kilo.ai",
    },
    {
        "id": "ovhcloud",
        "name": "OVHcloud AI Endpoints",
        "family": "ovhcloud",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
        "key_slot": "OVHCLOUD_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_NO_CARD,
        "free_category": STATUS_FREE_NO_CARD,
        "free_detail": "OVHcloud European AI endpoints: 2 RPM anonymous free tier (higher with registered token).",
        "rate_limits": "2 RPM anonymous",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 71,
        "default_model": "Meta-Llama-3.1-8B-Instruct",
        "source_url": "https://endpoints.ai.cloud.ovh.net",
    },
    {
        "id": "huggingface",
        "name": "Hugging Face",
        "family": "huggingface",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://router.huggingface.co/v1",
        "key_slot": "HUGGINGFACE_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_RATE_LIMITED,
        "free_category": STATUS_FREE_RATE_LIMITED,
        "free_detail": "Hugging Face Inference Router: rate-limited free access (~1,000 req/day) on shared GPUs.",
        "rate_limits": "~1,000 req/day",
        "context_length": 32768,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 72,
        "default_model": "meta-llama/Llama-3.2-3B-Instruct",
        "source_url": "https://huggingface.co/settings/tokens",
    },
    {
        "id": "aion",
        "name": "Aion Labs",
        "family": "aion",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.aionlabs.ai/v1",
        "key_slot": "AION_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_NO_CARD,
        "free_category": STATUS_FREE_NO_CARD,
        "free_detail": "Aion Labs proprietary models: 15 RPM, 20K tokens/day free allocation.",
        "rate_limits": "15 RPM / 20K TPD",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 73,
        "default_model": "aion-2.0",
        "source_url": "https://aionlabs.ai",
    },
    {
        "id": "agnes",
        "name": "Agnes AI",
        "family": "agnes",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://apihub.agnes-ai.com/v1",
        "key_slot": "AGNES_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_REGISTRATION,
        "free_category": STATUS_FREE_REGISTRATION,
        "free_detail": "Agnes AI (Sapiens Singapore): 30 RPM free tier on text-and-vision flash models.",
        "rate_limits": "30 RPM",
        "context_length": 65536,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 74,
        "default_model": "agnes-flash",
        "source_url": "https://agnes-ai.com",
    },
    {
        "id": "alibaba",
        "name": "Alibaba Cloud Model Studio",
        "family": "alibaba",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
        "key_slot": "ALIBABA_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_RENEWABLE_CREDITS,
        "free_category": STATUS_RENEWABLE_CREDITS,
        "free_detail": "Alibaba Cloud DashScope: trial token quota on Qwen and international model studio.",
        "rate_limits": "Trial token quota",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 75,
        "default_model": "qwen-plus",
        "source_url": "https://dashscope.console.aliyun.com",
    },
    {
        "id": "xai",
        "name": "xAI (Grok)",
        "family": "xai",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.x.ai/v1",
        "key_slot": "XAI_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_RENEWABLE_CREDITS,
        "free_category": STATUS_RENEWABLE_CREDITS,
        "free_detail": "xAI developer tier: $25/month recurring free credits resetting monthly for Grok models.",
        "rate_limits": "$25/month free credits",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 76,
        "default_model": "grok-2-mini",
        "source_url": "https://console.x.ai",
    },
    {
        "id": "chutes",
        "name": "Chutes.ai",
        "family": "chutes",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.chutes.ai/v1",
        "key_slot": "CHUTES_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_NO_CARD,
        "free_category": STATUS_FREE_NO_CARD,
        "free_detail": "Community-donated compute running DeepSeek-R1 and Llama 3.1 70B at $0.",
        "rate_limits": "Community fair use",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 77,
        "default_model": "deepseek-ai/DeepSeek-R1",
        "source_url": "https://chutes.ai",
    },
    {
        "id": "glhf",
        "name": "Glhf.chat",
        "family": "glhf",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://glhf.chat/api/openai/v1",
        "key_slot": "GLHF_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_NO_CARD,
        "free_category": STATUS_FREE_NO_CARD,
        "free_detail": "Glhf.chat community inference: unlimited rate for free models like Llama 3.1 70B.",
        "rate_limits": "Unlimited on free models",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 78,
        "default_model": "hf:meta-llama/Llama-3.1-70B-Instruct",
        "source_url": "https://glhf.chat",
    },
    {
        "id": "ai21",
        "name": "AI21 Labs",
        "family": "ai21",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.ai21.com/studio/v1",
        "key_slot": "AI21_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_RATE_LIMITED,
        "free_category": STATUS_FREE_RATE_LIMITED,
        "free_detail": "AI21 Labs free tier: Jamba 1.5 Mini/Large models with generous 256K context window.",
        "rate_limits": "200 RPM / 10 RPS",
        "context_length": 262144,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 79,
        "default_model": "jamba-1.5-mini",
        "source_url": "https://studio.ai21.com/account/api-key",
    },
    {
        "id": "nscale",
        "name": "Nscale",
        "family": "nscale",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://inference.api.nscale.com/v1",
        "key_slot": "NSCALE_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_NO_CARD,
        "free_category": STATUS_FREE_NO_CARD,
        "free_detail": "European AI compute: fair-use free tier on Llama 3.3 70B and DeepSeek R1.",
        "rate_limits": "Fair use throttling",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 80,
        "default_model": "meta-llama/Llama-3.3-70B-Instruct",
        "source_url": "https://console.nscale.com",
    },
    {
        "id": "nebius",
        "name": "Nebius",
        "family": "nebius",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.studio.nebius.com/v1",
        "key_slot": "NEBIUS_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_TRIAL_ONLY,
        "free_category": STATUS_TRIAL_ONLY,
        "free_detail": "Nebius AI Studio EU: trial credit granted upon account setup. Blocked in strict free-only mode.",
        "rate_limits": "Tier-based trial",
        "context_length": 131072,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 81,
        "default_model": "meta-llama/Meta-Llama-3.3-70B-Instruct",
        "source_url": "https://studio.nebius.com",
    },
    {
        "id": "cline",
        "name": "Cline",
        "family": "cline",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.cline.bot/v1",
        "key_slot": "CLINE_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_REGISTRATION,
        "free_category": STATUS_FREE_REGISTRATION,
        "free_detail": "Cline promotional free models: rotating selection for developer tooling.",
        "rate_limits": "Account promotional quota",
        "context_length": 65536,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 82,
        "default_model": "deepseek-v4-flash",
        "source_url": "https://cline.bot",
    },
    {
        "id": "scaleway",
        "name": "Scaleway",
        "family": "scaleway",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.scaleway.ai/v1",
        "key_slot": "SCALEWAY_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_UNKNOWN,
        "free_category": STATUS_UNKNOWN,
        "free_detail": "Scaleway Generative APIs: requires payment method verification. FREE STATUS: UNKNOWN.",
        "rate_limits": "Tier-based",
        "context_length": 65536,
        "requires_api_key": True,
        "requires_card": True,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 83,
        "default_model": "",
        "source_url": "https://console.scaleway.com",
    },
    {
        "id": "tencent",
        "name": "Tencent Hunyuan",
        "family": "tencent",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.hunyuan.cloud.tencent.com/v1",
        "key_slot": "TENCENT_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_REGISTRATION,
        "free_category": STATUS_FREE_REGISTRATION,
        "free_detail": "Tencent Cloud Hunyuan: hunyuan-lite model offered on free registration tier.",
        "rate_limits": "Free tier quota",
        "context_length": 32768,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 84,
        "default_model": "hunyuan-lite",
        "source_url": "https://cloud.tencent.com/product/hunyuan",
    },
    {
        "id": "arli",
        "name": "Arli AI",
        "family": "arli",
        "mode": "cloud",
        "api": "openai",
        "base_url": "https://api.arliai.com/v1",
        "key_slot": "ARLI_API_KEY",
        "discovery": "openai-models",
        "free_status": STATUS_FREE_RATE_LIMITED,
        "free_category": STATUS_FREE_RATE_LIMITED,
        "free_detail": "Arli AI developer free tier: rate-limited access on open-source Llama/Mistral.",
        "rate_limits": "Rate-limited developer tier",
        "context_length": 65536,
        "requires_api_key": True,
        "requires_card": False,
        "requires_phone": False,
        "enabled_default": False,
        "priority": 85,
        "default_model": "",
        "source_url": "https://arliai.com",
    },
]

PROVIDERS_BY_ID: dict[str, dict[str, Any]] = {item["id"]: item for item in PROVIDER_DEFS}

# Default conversation fallback order (local Qwen first, followed by free-tier clouds)
DEFAULT_FALLBACK_ORDER: tuple[str, ...] = (
    "ollama-local",
    "gemini-1",
    "gemini-2",
    "gemini-3",
    "groq",
    "openrouter",
    "nvidia-nim",
    "modelscope",
    "cloudflare",
    "pollinations",
    "mistral",
    "cohere",
    "cerebras",
    "deepseek",
    "siliconflow",
    "zai",
    "sambanova",
    "opencode",
    "llm7",
    "ollama-cloud",
    "kilo",
    "ovhcloud",
    "huggingface",
    "aion",
    "agnes",
    "alibaba",
    "xai",
    "chutes",
    "glhf",
    "ai21",
    "nscale",
    "nebius",
    "cline",
    "scaleway",
    "tencent",
    "arli",
)


def provider_def(provider_id: str) -> dict[str, Any] | None:
    return PROVIDERS_BY_ID.get(str(provider_id or ""))
